# Generated by Django 5.0.6 on 2024-06-07 15:57

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_user_role_change_requested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="arrive_date",
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="exit_date",
            field=django_jalali.db.models.jDateField(),
        ),
    ]
