# Generated by Django 5.0.6 on 2024-06-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_alter_order_arrive_date_alter_order_exit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="arrive_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="exit_date",
            field=models.DateField(),
        ),
    ]
